### ISSUE TITLE
Can't build libogg

### ISSUE THREAD

**Issue by basxto** [liberated-cortex/CCOSS_dependencies#3]
I get an error when I try to compile libogg.

[output](https://gist.github.com/basxto/37de91ef9a4b5d905da6f5df2a747d94)

I ran autoconf, but that did not change anything.

OS:  ArchLinux
Kernel: 5.2.3.arch1-1
automake: 1.16.1-1
libtool: 2.4.6+42+gb88cebd5-5
autoconf: 2.69-5

**Comment by Smilex** [comment]
Try again, I committed some generated files by mistake, and I suspect that's it. You might have to download the entire thing again

**Comment by basxto** [comment]
Thank you for your quick response, but I still get the same message.
It looks more like the definition gets built with my installed libtool and then run with the libtool it gets shipped with.

```terminal
$ libtool --version
libtool (GNU libtool) 2.4.6.42-b88ce
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.

$ ./libogg-1.3.3/libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by basxto** [comment]
Well it’s not a fix, but I found a work around:
```
cd CCOSS_dependencies/libogg-1.3.3/
rm ./ltmain.sh
ln -s /usr/bin/libtool ./ltmain.sh
```

**Comment by basxto** [comment]
Where is that libogg from?
It’s not https://gitlab.xiph.org/xiph/ogg/-/tags/v1.3.3

That would’ve been built like that:
```sh
#!/bin/bash

pushd $PWD/libogg-1.3.3
    ./autogen.sh
    ./configure --prefix=$PWD/install --enable-shared=no
    make
    make install
popd
```
